import json
import logging
from typing import Any, Dict, List, Tuple

from app.ai.client import get_async_ai_client
from app.ai.prompts import get_routing_system_prompt
from app.config import IntentType, settings

logger = logging.getLogger(__name__)


def _simplify_content_for_routing(content: Any) -> str:
    """Convert multi-part content (list of dicts) to simple text for routing LLM.

    The routing LLM expects simple text, but message_converter produces
    content as lists of {type, text} dicts. Extract just the text.

    Also filters out routing metadata injected during the routing phase
    ("Understanding your question…" and the intent reasoning), so they
    don't leak back into the routing LLM on subsequent turns.

    The metadata strings originate in:
      - chat.py:_build_routing_parts()  ("Understanding your question…")
      - chat.py:_emit_routing_phase()   (intent reasoning text)
    """
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        texts = []
        for part in content:
            if isinstance(part, dict) and part.get("type") == "text":
                text = part.get("text", "")
                if not text:
                    continue
                # Skip routing UX text injected by _build_routing_parts()
                if text.startswith("Understanding your question"):
                    continue
                # Skip intent-reasoning strings generated by the router.
                # These typically start with "User is …" or "The user is …".
                if (
                    text.startswith("User is ")
                    or text.startswith("The user is")
                    or (text.startswith("User ") and "asking" in text[:50])
                ):
                    continue
                texts.append(text)
        return "\n".join(texts)
    return str(content)


async def check_intent(messages: List[Dict[str, Any]]) -> Tuple[IntentType, str]:
    """
    Analyzes the user's latest message and conversation context to determine
    if it requires the Research Planner (Data360 tools) or can be handled
    via Direct Chat (Fast-Path).

    Returns:
        (intent, reasoning): intent and a brief explanation for the frontend.
    """

    client = get_async_ai_client()

    system_prompt = get_routing_system_prompt()

    try:
        # We only need the last few messages for intent
        limit = settings.ROUTING_HISTORY_LIMIT
        if len(messages) > limit:
            recent_history = messages[-limit:]
        else:
            recent_history = messages

        # Build clean, simple messages for routing LLM.
        # The routing LLM just needs user/assistant text to decide intent.
        # We must strip: tool messages, tool_calls, multi-part content structures.
        routing_messages = []
        for msg in recent_history:
            role = msg.get("role")
            # Skip tool messages entirely
            if role == "tool":
                continue
            # Build a clean message with just role + simple text content
            content = _simplify_content_for_routing(msg.get("content", ""))
            if not content:
                continue  # Skip messages with no usable text
            # Only include role and content - no tool_calls, no other keys
            routing_messages.append({"role": role, "content": content})

        logger.debug(
            "Routing with %d messages: %s",
            len(routing_messages),
            json.dumps(
                [
                    {
                        "role": m["role"],
                        "content": m["content"][:120] + "..."
                        if len(m["content"]) > 120
                        else m["content"],
                    }
                    for m in routing_messages
                ],
                ensure_ascii=False,
            ),
        )

        response = await client.chat.completions.create(
            model=settings.ROUTING_MODEL,
            messages=[{"role": "system", "content": system_prompt}, *routing_messages],
            response_format={"type": "json_object"},
            temperature=0,
            max_tokens=200,
            stream=False,
        )

        raw_content = response.choices[0].message.content
        finish_reason = response.choices[0].finish_reason
        logger.debug("Routing raw response (finish_reason=%s): %r", finish_reason, raw_content)

        result = json.loads(raw_content)
        intent = IntentType(result.get("intent", IntentType.RESEARCH))
        reasoning = result.get("reasoning", "").strip()

        logger.info("Intent Routing: %s (Reason: %s)", intent, reasoning)
        return (intent, reasoning)

    except json.JSONDecodeError as json_err:
        content = response.choices[0].message.content if "response" in locals() else "No response"
        logger.error(
            "Error parsing routing response as JSON: %s. Response content: %r",
            str(json_err),
            content,
        )
        return (IntentType.RESEARCH, "")
    except Exception as e:
        logger.error("Error in intent routing: %s. Defaulting to RESEARCH.", str(e))
        return (IntentType.RESEARCH, "")
