import json
import logging
from typing import Any, Dict, List, Tuple

from langchain_core.messages import AIMessage as LCAIMessage
from langchain_core.messages import HumanMessage, SystemMessage

from app.ai.prompts import get_routing_system_prompt
from app.config import IntentType, settings

logger = logging.getLogger(__name__)


def _simplify_content_for_routing(content: Any) -> str:
    """Convert multi-part content (list of dicts) to simple text for routing LLM.

    The routing LLM expects simple text, but message_converter produces
    content as lists of {type, text} dicts. Extract just the text.

    Also filters out routing metadata injected during the routing phase
    ("Understanding your question…" and the intent reasoning), so they
    don't leak back into the routing LLM on subsequent turns.

    The metadata strings originate in:
      - chat.py:_build_routing_parts()  ("Understanding your question…")
      - chat.py:_emit_routing_phase()   (intent reasoning text)
    """
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        texts = []
        for part in content:
            if isinstance(part, dict) and part.get("type") == "text":
                text = part.get("text", "")
                if not text:
                    continue
                # Skip routing UX text injected by _build_routing_parts()
                if text.startswith("Understanding your question"):
                    continue
                # Skip intent-reasoning strings generated by the router.
                # These typically start with "User is …" or "The user is …".
                if (
                    text.startswith("User is ")
                    or text.startswith("The user is")
                    or (text.startswith("User ") and "asking" in text[:50])
                ):
                    continue
                texts.append(text)
        return "\n".join(texts)
    return str(content)


async def check_intent(
    messages: List[Dict[str, Any]],
    session_summary: str = "",
) -> Tuple[IntentType, str, List[str], str]:
    """Classify the user's latest message into one of five routing intents.

    Uses a ``ChatLiteLLM`` instance (via :func:`get_routing_llm`) so that the
    LLM call participates in LangChain's callback system.  When invoked from
    inside ``router_node`` — a LangGraph node — LangGraph automatically tags the
    resulting ``on_chat_model_end`` event with ``langgraph_node="router"``, so
    token usage is accumulated by the SSE bridge through the standard path
    (no manual ``router_usage`` plumbing required).

    Args:
        messages:        Conversation history in OpenAI format.
        session_summary: Optional compressed summary of earlier turns — injected
                         as a user message so the router retains context
                         (country, topic, etc.) even when the full history
                         exceeds ROUTING_HISTORY_LIMIT.

    Returns:
        (intent, reasoning, missing_slots, detected_language):
          - intent:            one of RESEARCH, DIRECT, CLARIFY, OUT_OF_SCOPE, EXPLAIN
          - reasoning:         brief English explanation from the routing LLM
          - missing_slots:     slot names absent when intent is CLARIFY, else []
          - detected_language: full English name of the user's language (e.g. "French")
    """
    # Import here to avoid a module-level circular dependency
    # (routing.py ← nodes/router.py ← pipeline.py ← llm_factory.py would
    # all be loaded in the same package; deferred import keeps the chain clean).
    from app.ai.graph.llm_factory import get_routing_llm

    logger.info("[routing] check_intent start messages_count=%d", len(messages))

    system_prompt = get_routing_system_prompt()

    try:
        # Only the most recent turns are needed for intent classification.
        limit = settings.ROUTING_HISTORY_LIMIT
        recent_history = messages[-limit:] if len(messages) > limit else messages

        # Build a clean, minimal message list for the routing LLM.
        # Strip tool messages, tool_calls, and multi-part content structures.
        routing_messages: list[dict] = []

        # Prepend session summary (if any) so the router retains context even
        # after the history window truncates older turns.
        if session_summary:
            routing_messages.append(
                {
                    "role": "user",
                    "content": (
                        "[CONVERSATION SUMMARY — context from earlier turns]\n" + session_summary
                    ),
                }
            )

        for msg in recent_history:
            role = msg.get("role")
            if role == "tool":
                continue  # tool results carry no useful intent signal
            content = _simplify_content_for_routing(msg.get("content", ""))
            if not content:
                continue
            routing_messages.append({"role": role, "content": content})

        logger.info(
            "[routing] calling routing LLM model=%s routing_messages=%d",
            settings.ROUTING_MODEL,
            len(routing_messages),
        )
        logger.debug(
            "Routing with %d messages: %s",
            len(routing_messages),
            json.dumps(
                [
                    {
                        "role": m["role"],
                        "content": (
                            m["content"][:120] + "..." if len(m["content"]) > 120 else m["content"]
                        ),
                    }
                    for m in routing_messages
                ],
                ensure_ascii=False,
            ),
        )

        # Convert simplified dicts → LangChain messages for the LLM call.
        lc_messages: list = [SystemMessage(content=system_prompt)]
        for msg in routing_messages:
            role = msg["role"]
            content = msg["content"]
            if role == "user":
                lc_messages.append(HumanMessage(content=content))
            elif role == "assistant":
                lc_messages.append(LCAIMessage(content=content))
            # Other roles (system duplicates, etc.) are skipped.

        llm = get_routing_llm()
        response_msg: LCAIMessage = await llm.ainvoke(lc_messages)
        raw_content: str = str(response_msg.content or "")

        logger.info("[routing] routing LLM response received")
        logger.debug("Routing raw response: %r", raw_content)

        result = json.loads(raw_content)
        raw_intent = result.get("intent", IntentType.RESEARCH.value)
        try:
            intent = IntentType(raw_intent)
        except ValueError:
            logger.warning("[routing] unknown intent value=%r, defaulting to RESEARCH", raw_intent)
            intent = IntentType.RESEARCH

        reasoning: str = result.get("reasoning", "").strip()
        missing_slots: List[str] = result.get("missing_slots", [])
        if not isinstance(missing_slots, list):
            missing_slots = []
        detected_language: str = result.get("detected_language", "English") or "English"

        logger.info(
            "[routing] check_intent done intent=%s missing_slots=%s language=%s reasoning_len=%d",
            intent,
            missing_slots,
            detected_language,
            len(reasoning),
        )
        return (intent, reasoning, missing_slots, detected_language)

    except json.JSONDecodeError as json_err:
        raw = raw_content if "raw_content" in locals() else "No response"
        logger.error(
            "Error parsing routing response as JSON: %s. Response content: %r",
            str(json_err),
            raw,
        )
        return (IntentType.RESEARCH, "", [], "English")
    except Exception as e:
        logger.error("Error in intent routing: %s. Defaulting to RESEARCH.", str(e))
        return (IntentType.RESEARCH, "", [], "English")
