import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage();
await page.goto('http://localhost:3001');
await page.waitForTimeout(2000);
await page.getByPlaceholder(/message/i).fill('What is the GDP for Japan and the Philippines?');
await page.getByPlaceholder(/message/i).press('Enter');
await page.waitForSelector('.data360-mcp-ui-reset', { timeout: 30000 });
const html = await page.$eval('.data360-mcp-ui-reset', el => el.innerHTML);
console.log(html);
await browser.close();
