"""add_user_disabled_column

Revision ID: 9bab245e8167
Revises: k2m3n4o5p6q7
Create Date: 2026-08-01 19:57:15.693715

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9bab245e8167"
down_revision: Union[str, None] = "k2m3n4o5p6q7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User",
        sa.Column("disabled", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "disabled")
    # ### end Alembic commands ###
